repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  #- repo: https://github.com/codespell-project/codespell
  #  rev: v2.2.6
  #  hooks:
  #    - id: codespell
  #      additional_dependencies:
  #        - tomli

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 'v2.6.0'
    hooks:
      - id: pyproject-fmt

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.6.0
  #  hooks:
  #    - id: mypy
  #      args:
  #        - --ignore-missing-imports
  #        - --install-types # See mirrors-mypy README.md
  #        - --non-interactive
  #      additional_dependencies: [types-requests]
